from pathlib import Path
import json,base64
R=Path(__file__).resolve().parent
mesh=(R/'drawings/mesh.json').read_text()
html='''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ORBITAL POD / E1 - 3D review</title>
<style>*{box-sizing:border-box}body{margin:0;background:#eef2f4;color:#182e3d;font:15px/1.7 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}h1{font-size:25px;margin:0;font-weight:500}small{color:#526977}.tools{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}button{font:inherit;border:1px solid #b8c6ce;border-radius:5px;padding:6px 16px;background:#fff;color:#263e4d;cursor:pointer}button[aria-pressed=true]{background:#243e4b;color:#fff}canvas{display:block;width:100%;height:540px;touch-action:none;background:#e9eef1;border-radius:8px;cursor:grab}canvas:active{cursor:grabbing}.detail{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:18px}.detail p{margin:0 0 8px}dl{display:grid;grid-template-columns:115px 1fr;margin:0;gap:5px}dt{color:#526977}dd{margin:0}.note{border-top:1px solid #cbd6dd;margin-top:20px;padding-top:16px;color:#526977;font-size:13px}#fallback{display:none;width:100%}@media(max-width:650px){main{padding:16px}.detail{grid-template-columns:1fr}canvas{height:390px}h1{font-size:21px}}</style>
<main><header><h1>ORBITAL POD / E1</h1><small>黒色 MJF PA12 · 機構設計 v0.3</small></header>
<div class="tools" aria-label="モデル表示"><button id="outside" aria-pressed="true">外観</button><button id="inside" aria-pressed="false">内部</button><button id="exploded" aria-pressed="false">分解</button><button id="display" aria-pressed="false">画面保持</button><button id="front">正面側</button><button id="rear">背面側</button></div>
<canvas id="model" aria-label="透明OLED付きリマッパーの3D形状。ドラッグで回転し、表示ボタンで筐体の内外を確認できます。"></canvas><img id="fallback" alt="CAD外観図" src="data:image/png;base64,__IMAGE__">
<small>ドラッグ：回転　ホイール：拡大縮小　部品は機構検討用の簡略外形です。</small>
<div class="detail"><div><dl><dt>台座</dt><dd>104 × 約87.4 mm・丸いPod</dd><dt>全高</dt><dd>約61.3 mm（足を含む）</dd><dt>画面</dt><dd>机面から65°・背面開放</dd><dt>PCB</dt><dd>74 × 58 × 1.6 mm</dd></dl></div><div><p id="caption" aria-live="polite">背面にUSB-CとUSB-A。手前にノブと戻る、左奥に凹んだリセットボタンを配置。</p><small>分解表示は部品の関係を示すための移動です。実際の組立順序はPDFを参照してください。</small></div></div>
<div class="note">試作設計です。Glass2は機械寸法図を基準にモデル化。公式仕様表との寸法差、端子高さ、軸、押し子、インサート穴は実物で照合してください。回路図・電気配線パターンは含みません。</div></main>
<script>
const mesh=__MESH__;
const canvas=document.getElementById('model'),gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});
if(!gl){canvas.hidden=true;document.getElementById('fallback').style.display='block'}else{
function shader(type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const vs=shader(gl.VERTEX_SHADER,`attribute vec3 position;attribute vec3 normal;uniform mat3 camera;uniform vec3 shift;uniform vec3 center;uniform vec2 scale;varying vec3 n;void main(){vec3 p=camera*(position+shift-center);gl_Position=vec4(p.x*scale.x,p.y*scale.y,-p.z/250.0,1.0);n=normal;}`);
const fs=shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 n;uniform vec4 color;void main(){float light=.58+.42*max(0.0,dot(normalize(n),normalize(vec3(-.3,-.45,.84))));gl_FragColor=vec4((color.rgb*.85+.075)*light,color.a);}`);
const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
const loc={};['camera','shift','center','scale','color'].forEach(x=>loc[x]=gl.getUniformLocation(program,x));
const pos=gl.getAttribLocation(program,'position'),nor=gl.getAttribLocation(program,'normal');gl.enableVertexAttribArray(pos);gl.enableVertexAttribArray(nor);
const objects=mesh.map(o=>{let normals=o.v.map(()=>[0,0,0]);for(const f of o.f){let a=o.v[f[0]],b=o.v[f[1]],c=o.v[f[2]],u=b.map((v,i)=>v-a[i]),v=c.map((v,i)=>v-a[i]);let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];for(let i of f)for(let j=0;j<3;j++)normals[i][j]+=n[j]}normals=normals.map(n=>{let l=Math.hypot(...n)||1;return n.map(x=>x/l)});let data=[];for(const f of o.f)for(let i of f)data.push(...o.v[i],...normals[i]);let buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);return {...o,buf,count:data.length/6}});
let mode='outside',az=-1.134,el=.384,zoom=1;
const hide=new Set(['01_upper_shell','03_display_carrier','04_knob','05_back_button','06_reset_button','OLED_glass','OLED_lower_housing','OLED_Grove_plug','OLED_PCB_frame']);
const shifts={'01_upper_shell':[0,0,37],'03_display_carrier':[0,18,24],'02_bottom':[0,0,-12],'04_knob':[0,0,60],'05_back_button':[0,0,56],'06_reset_button':[0,0,56]};
function draw(){let ratio=Math.min(devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*ratio),h=Math.round(canvas.clientHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.clearColor(.914,.933,.945,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.disable(gl.CULL_FACE);
let a=az,e=el;gl.uniformMatrix3fv(loc.camera,false,new Float32Array([-Math.sin(a),-Math.cos(a)*Math.sin(e),Math.cos(a)*Math.cos(e),Math.cos(a),-Math.sin(a)*Math.sin(e),Math.sin(a)*Math.cos(e),0,Math.cos(e),Math.sin(e)]));let range=(mode==='exploded'?87:mode==='display'?35:57)/zoom;gl.uniform2f(loc.scale,1/range*h/w,1/range);gl.uniform3f(loc.center,0,mode==='display'?19:-8,mode==='exploded'?44:mode==='display'?35:29);
let arr=objects.filter(o=>mode==='display'?(o.name.startsWith('OLED_')||o.name==='03_display_carrier'):(mode!=='inside'||!hide.has(o.name)));arr.sort((a,b)=>(a.name==='OLED_glass')-(b.name==='OLED_glass'));
for(const o of arr){let sh=[0,0,0];if(mode==='exploded'){sh=shifts[o.name]||sh;if(o.name.startsWith('OLED_'))sh=[0,0,38]}gl.uniform3fv(loc.shift,sh);let alpha=o.name==='OLED_glass'?.27:1;gl.uniform4f(loc.color,...o.color,alpha);if(alpha<1){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.enable(gl.CULL_FACE)}else{gl.disable(gl.BLEND);gl.depthMask(true);gl.disable(gl.CULL_FACE)}gl.bindBuffer(gl.ARRAY_BUFFER,o.buf);gl.vertexAttribPointer(pos,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(nor,3,gl.FLOAT,false,24,12);gl.drawArrays(gl.TRIANGLES,0,o.count)}gl.depthMask(true)}
for(const m of ['outside','inside','exploded','display'])document.getElementById(m).onclick=()=>{mode=m;for(const x of ['outside','inside','exploded','display'])document.getElementById(x).setAttribute('aria-pressed',x===m);document.getElementById('caption').textContent={outside:'背面にUSB-CとUSB-A。手前にノブと戻る、左奥に凹んだリセットボタンを配置。',inside:'左にPico、奥中央にXIAO、奥右にUSB-A。基板裏の作業空間と固定支柱を確保。',exploded:'造形6部品と電子部品の関係を表示。画面ホルダーと底蓋はねじで着脱できます。',display:'Glass2の基板枠と下部回路を背面ホルダーで保持。既存の取付穴を利用し、左右の足を上ケースへ固定します。'}[m];zoom=1;draw()};
document.getElementById('front').onclick=()=>{az=-1.134;el=.384;draw()};document.getElementById('rear').onclick=()=>{az=1.05;el=.40;draw()};
let last=null;canvas.onpointerdown=e=>{last=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(last){az+=(e.clientX-last[0])*.008;el=Math.max(-.25,Math.min(1.45,el+(e.clientY-last[1])*.008));last=[e.clientX,e.clientY];draw()}};canvas.onpointerup=canvas.onpointercancel=()=>last=null;canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.5,Math.min(2.4,zoom*Math.exp(-e.deltaY*.001)));draw()},{passive:false});new ResizeObserver(draw).observe(canvas);draw();window.orbitalE1={draw,getMode:()=>mode};
}
</script></html>'''
html=html.replace('__MESH__',mesh).replace('__IMAGE__',base64.b64encode((R/'drawings/perspective.png').read_bytes()).decode())
(R/'remapper_3d_viewer.html').write_text(html)
print('viewer generated')
